kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "azure-spot-monitor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole 
  name: {{ .Release.Name }}-clusterrole 
  apiGroup: rbac.authorization.k8s.io