{{- $subscriptionId := .Values.azure.subscriptionId | required ".Values.azure.subscriptionId is required." -}}
{{- $clusterName := .Values.azure.clusterName | required ".Values.azure.clusterName is required." -}}
{{- $resourceGroupName := .Values.azure.resourceGroupName  | required ".Values.azure.resourceGroupName is required." -}}
{{- $clientId := .Values.azure.clientId | required ".Values.azure.clientId  is required." -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  azuure-spot-monitor.yaml: |
    subscription:
      id: "{{ $subscriptionId }}"
    cluster:
      name: "{{ $clusterName }}"
    resource:
      group: "{{ $resourceGroupName }}"
    azure:
      client:
        id: "{{ $clientId }}"
    {{- if .Values.extraConfig }}
    {{- toYaml .Values.extraConfig | nindent 4 }}
    {{- end }}