apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus-operator
  name: {{ .Release.Name }}-servicemonitor
spec:
  endpoints:
  - port: http
    interval: 20s
    path: /metrics
  selector:
    matchLabels:
      {{- include "azure-spot-monitor.selectorLabels" . | nindent 4 }}